#!/usr/bin/env node
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..");
const outputPath = path.join(repoRoot, "llms-full.txt");

const sourceFiles = [
  { title: "Project README", file: "README.md" },
  { title: "Product terminology", file: "CONTEXT.md" },
  { title: "User workflows", file: "docs/WORKFLOWS.md" },
  { title: "CLI reference", file: "docs/CLI.md" },
  { title: "Public roadmap", file: "docs/ROADMAP.md" },
  { title: "CLI package README", file: "packages/cli/README.md" },
  { title: "Core package README", file: "packages/core/README.md" },
  { title: "Agent pack README", file: "packages/agent-pack/README.md" },
  { title: "Setup package README", file: "packages/setup/README.md" },
];

const intro = `# OKF Harness full LLM context

> Generated from public repository documentation. Do not edit this file by hand. Run \`pnpm docs:llms\` after changing the source docs listed below.

OKF Harness is an agent-first, local-first, terminal-native harness for maintaining OKF-compatible LLM Wikis through supported agents.

OKF Harness is independent. It is not affiliated with or endorsed by Andrej Karpathy or Google, and it is not an official Open Knowledge Format implementation.

This file is meant for AI tools that need one public context bundle. It excludes private maintainer notes, generated release checks, local machine paths, and internal implementation documents.

## Source files

${sourceFiles.map((source) => `- ${source.file}: ${source.title}`).join("\n")}
`;

const sections = [];
for (const source of sourceFiles) {
  const sourcePath = path.join(repoRoot, source.file);
  const content = await readFile(sourcePath, "utf8");
  sections.push(
    `## ${source.title}\n\nSource path: \`${source.file}\`\n\n${demoteHeadings(content.trim(), 2)}`,
  );
}

const nextContent = `${intro}\n${sections.join("\n\n")}\n`;

if (process.argv.includes("--check")) {
  const currentContent = await readFile(outputPath, "utf8").catch(() => "");
  if (currentContent !== nextContent) {
    console.error("llms-full.txt is out of date. Run pnpm docs:llms.");
    process.exitCode = 1;
  } else {
    console.log("llms-full.txt is up to date.");
  }
} else {
  await writeFile(outputPath, nextContent);
  console.log(`wrote ${path.relative(repoRoot, outputPath)}`);
}

function demoteHeadings(markdown, levels) {
  let inFence = false;
  return markdown
    .split("\n")
    .map((line) => {
      if (line.startsWith("```")) {
        inFence = !inFence;
        return line;
      }
      if (inFence) {
        return line;
      }
      return line.replace(/^(#{1,6})(\s+)/, (_, hashes, space) => {
        return `${"#".repeat(Math.min(6, hashes.length + levels))}${space}`;
      });
    })
    .join("\n");
}
